version: '3.8'
services:
  api_users:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: users
    ports:
      - 8000:8000
    environment:
      - DB_HOST=${DB_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MYPORT_TRANSITIONS=${MYPORT_TRANSITIONS}
      - MYPORT_USERS=${MYPORT_USERS}
      - ROUTE_NAME_USERS=${ROUTE_NAME_USERS}
      - ROUTE_NAME_TRANSITIONS=${ROUTE_NAME_TRANSITIONS}
    volumes:
      - ./users:/usr/src/app
      - /usr/src/app/node_modules
  api_transitions:
    build:
      context: ./transitions
      dockerfile: Dockerfile
    container_name: transitions
    ports:
      - 5000:5000
    environment:
      - DB_HOST=${DB_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MYPORT_TRANSITIONS=${MYPORT_TRANSITIONS}
      - MYPORT_USERS=${MYPORT_USERS}
      - ROUTE_NAME_USERS=${ROUTE_NAME_USERS}
      - ROUTE_NAME_TRANSITIONS=${ROUTE_NAME_TRANSITIONS}
    volumes:
      - ./transitions:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres:15.2
    container_name: db_tst
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # volumes:
    #   - nps_data:/var/lib/postgresql/data
    #   - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  nps_data: {}
